export const productOperations = {
    PRODUCT: 'PRODUCT',
  PRODUCT_LOADING: 'PRODUCT_LOADING',
        PRODUCT_SUCCESS: 'PRODUCT_SUCCESS',
        PRODUCT_FAILURE: 'PRODUCT_FAILURE',
        PRODUCT_RESET: 'PRODUCT_RESET',
};

export const cartOperations = {
       GET_CART : "GET_CART",
       GET_CART_LOADING : "GET_CART_LOADING",
       GET_CART_SUCCESS : "GET_CART_SUCCESS",
       GET_CART_FAILURE : "GET_CART_FAILURE",
  
       DECREMENT_CART:'DECREMENT_CART',
       INCREMENT_CART:'INCREMENT_CART',
       REMOVE_CART:'REMOVE_CART',
};

export const searchOperations = {
    SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
    SET_CATEGORY: 'SET_CATEGORY',
};